import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastContainer
          position="bottom-center"
          autoClose={5000}
          toastClassName="custom-toast"
        />
        <Suspense>{children}</Suspense>
      </body>
    </html>
  );
}
